# Teacher version

## Warm-up

Consider the following example. How would you write the program to solve this problem?

<em>
We want to ask the user for a password, but make sure that the password is given is valid. The password must be at least 8 characters. If they don't give a valid password, they should be reprompted. We want to user to be able to try an infinite number of times until they give a valid password.
</em>

# Part 1: While Loops

While loops, much like for loops can be used to execute code repeatedly. Check out the explanation and example from W3Schools<sup>1</sup>

<blockquote>
With the <code>while</code> loop we can execute a set of statements as long as a condition is true.


Print i as long as i is less than 6: 
<pre>
<code>i = 1
while i < 6:
  print(i)
  i += 1</code>
</pre>

Note: remember to increment i, or else the loop will continue forever.

The while loop requires relevant variables to be ready, in this example we need to define an indexing variable, i, which we set to 1.
</blockquote>

In this case the **condition** is `i < 6`. So, as long as `i < 6` is `True`, the coded will run. As soon as `i < 6` becomes `False`, it will stop and move on with the code. Now, run the code in the example to see the output

In [1]:
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5

1. How many times does the loop execute? Write your answer below

### Your Response


The **condition** is evaluated 6 times, and the loop is **executed** 5 times. 

1.   `i` is 1, `i < 6` is `True`, `1` is printed, `i` becomes `2`
2.   `i` is 2, `i < 6` is `True`, `2` is printed, `i` becomes `3`
3.   `i` is 3, `i < 6` is `True`, `3` is printed, `i` becomes `4`
4.   `i` is 4, `i < 6` is `True`, `4` is printed, `i` becomes `5`
5.   `i` is 5, `i < 6` is `True`, `5` is printed, `i` becomes `6`
6.   `i` is 6, `i < 6` is `False` (`6` is not less than `6`), the inside of the loop is not executed, nothing is printed and the program continues

2. Now, what happens if we add a `print(i)` to the end? Think about your answer before running the code.

In [2]:
i = 1
while i < 6:
  print(i)
  i += 1

# here we are, after the while loop
print(i)

1
2
3
4
5
6

### Your Answer Here

6 will be printed at the end

3. Now, write a small script using a `while` loop to count down from 10. Start with a variable `i` at `10` and print each value of `i` as it counts down to `1`. The last number to be printed should be `1`.

In [3]:
# Your Code Here
i = 10
while i > 0: 
  print(i)
  i -= 1

10
9
8
7
6
5
4
3
2
1

4. Now, declare a variable `a` with value `3` and another variable `b` with value `2`. Using a `while` loop, determine how many times you can add `a` to `b` before `b` reaches `100`. 

*HINT: you may need to use another variable, `num_additions`*

In [4]:
# Your Code Here
a = 4
b = 3
num_additions = 0
while b < 100: 
  b += a
  num_additions += 1

print("b reached 100 after:", num_additions, "additions of a")

b reached 100 after: 25 additions of a

# Part 2: Problems


## Basketball Stars

One common use of coding is in the word of sports statistics. Here we have some data<sup>2</sup> about two NBA starts: Steph Curry and LeBron James. Below, we have the **number of points** each played scored in each game of their first season (2003 for LeBron and 2009 for Steph). 


This data can be accessed similar to the way we accessed the daeta in lab 1:
```
# prints the number of points LeBron scored
# in his FIRST game
print(LeBron[0])

# prints the number of points LeBron scored
# in his SECOND game
print(LeBron[1])

# prints the number of points LeBron scored
# in his 50th game
print(LeBron[49])
```

In [5]:
# data, MAKE SURE TO RUN THIS CELL
LeBron_first_season = [25, 21, 8, 7, 23, 17, 17, 18, 10, 22, 14, 28, 19, 15, 15, 6, 33, 19, 4, 8, 18, 23, 37, 27, 17, 36, 32, 22, 34, 18, 32, 22, 14, 14, 21, 19, 16, 27, 29, 29, 16, 27, 20, 38, 12, 32, 14, 14, 24, 9, 16, 32, 22, 21, 11, 30, 18, 24, 19, 24, 34, 14, 26, 17, 14, 15, 25, 16, 41, 18, 28, 20, 34, 21, 14, 24, 10, 27, 17]
Steph_first_season = [38, 23, 24, 14, 27, 25, 33, 36, 34, 21, 31, 34, 40, 32, 34, 25, 25, 12, 23, 14, 43, 27, 33, 44, 23, 36, 26, 25, 29, 34, 26, 29, 14, 48, 28, 29, 23, 35, 41, 37, 36, 32, 28, 37, 37, 32, 12, 22, 32, 22, 36, 47, 32, 32, 43, 22, 33, 20, 36, 36, 22, 26, 40, 23, 30, 29, 32, 29, 15, 38, 27, 34, 23, 27, 42, 19]

1. Using a `while` loop, determine how many games it took LeBron to reach `500` total points.

In [6]:
# Your Code Here
LeBron_total_points = 0
LeBron_game = 0
while LeBron_total_points < 500: 
  LeBron_total_points += LeBron_first_season[LeBron_game]
  LeBron_game += 1

# important: why LeBron_game and not LeBron_game + 1?
print("LeBron reached 300 points in his game number", LeBron_game, "after which he had", LeBron_total_points)

LeBron reached 300 points in his game number 27 after which he had 519

2. Using a `while` loop, determine how many games it took Steph to reach `500` total points.

In [7]:
# Your Code Here
# How many did it take for LeBron to reach 500?
Steph_total_points = 0
Steph_game = 0
while Steph_total_points < 500: 
  Steph_total_points += Steph_first_season[Steph_game]
  Steph_game += 1

# important: why Steph_game and not Steph_game + 1?
print("Steph reached 300 points in his game number", Steph_game, "after which he had", Steph_total_points)

Steph reached 300 points in his game number 18 after which he had 508

3. Who was reached 500 faster? Can you calculate the average points per game scored for each person up until the game where they reached 500 points?

In [8]:
# Your Code Here
first_reached = "Steph" if Steph_game < LeBron_game else "Lebron"
print("Therefore,", first_reached,"reached first.")

# Calculate the average points per game
LeBron_average = LeBron_total_points / (LeBron_game)
Steph_average = Steph_total_points / (Steph_game)
print("Lebron scored an average of,", LeBron_average, "points per game up until this point")
print("Steph scored an average of,", Steph_average, "points per game up until this point")

Therefore, Steph reached first.
Lebron scored an average of, 19.22222222222222 points per game up until this point
Steph scored an average of, 28.22222222222222 points per game up until this point

4. The 2022-2023 NBA season recieved a lot of attention for the high number of games were a single player scored 40 or more points. This is something both LeBron and Steph have been doing for a long time now. Using `while` loops, find the number of the **first** time each of these players scored at least 40 points in one game.

In [9]:
# Your Code Here
LeBron_game = 0
while LeBron_first_season[LeBron_game] < 40:
  LeBron_game += 1

Steph_game = 0
while Steph_first_season[Steph_game] < 40:
  Steph_game += 1

print("LeBron's first 40+ point game was his game number", LeBron_game)
print("Steph's first 40+ point game was his game number", Steph_game)

LeBron's first 40+ point game was his game number 68
Steph's first 40+ point game was his game number 12

5. How many 40+ point games did each player have in their first season? You may use a `while` or a `for` loop for this, your choice.

In [10]:
# Your Code Here
LeBron_40_games = 0
for game in LeBron_first_season:
  if game >= 40:
    LeBron_40_games += 1

Steph_40_games = 0
for game in Steph_first_season:
  if game >= 40:
    Steph_40_games += 1

print("LeBron's first season, he had", LeBron_40_games, "40+ point games")
print("Steph's first season, he had", Steph_40_games, "40+ point games")

LeBron's first season, he had 1 40+ point games
Steph's first season, he had 9 40+ point games

6. Who would you say had the stronger first season **in terms of their scoring**? Why? You are welcome to do more calculations to justify your answer.

In [11]:
# Your Code Here
LeBron_mean = sum(LeBron_first_season)/len(LeBron_first_season)
Steph_mean = sum(Steph_first_season)/len(Steph_first_season)
print("LeBron's average points per games in his first season:", LeBron_mean)
print("Steph's average points per games in his first season:", Steph_mean)

LeBron's average points per games in his first season: 20.936708860759495
Steph's average points per games in his first season: 29.710526315789473

#### Your Response Here

From the metrics we've calculated already, we could say that Steph had a more dominant first season. He had 8 more 40+ point games and up to 500+ points seemed to be scoring points faster. If we want, we could calculate the average number of points per game for each player for the whole season, which would also show Steph scoring more per game than LeBron in his first season.

### Prime Numbers

Recall that prime numbers are really special in that they have factors other than 1 and themselves. 

We're to write code to decide if a number is prime. 


#### How can we tell if a number is prime?
The process for determining if number `n` is prime will be something like this: 

1.   Check if `n` is divisible by `2`, if it is, then `n` isn't prime
2.   Check if `n` is divisible by `3`, if it is, then `n` isn't prime
3.   Check if `n` is divisible by `4`, if it is, then `n` isn't prime
<br>...<br>
Check if `n` ia divisible by `int(n/2)`, if it ISNT, then `n` IS prime

But how can we tell if a number number is divisible by another? Well, remember that in coding we have **modulo** division which finds the remainder of the division of two numbers. Note that if a number is divisible by another, than the remainder of the division of these two numbers will be 0. 

1. Complete the following code to determine if `n` is divisible by `x`.

In [12]:
x = 13 
n = 5356
if n % x == 0:
  print(n, "is divisible by", x)
else: 
  print(n, "is NOT divisible by", x)

5356 is divisible by 13

2. Write a script to determine if the number `n` is prime.

In [13]:
n = 313
# Your Code Here
prime = True
for i in range(2, int(n/2)):
  if n % i == 0:
    prime = False

if prime: 
  print(n, "is prime")    
else: 
  print(n, "is NOT prime")

313 is prime

3. Calculate the number of prime numbers under 100?

In [14]:
# Your Code Here
num_primes = 0

# 1 is not a prime number, so we don't test it
for n in range(2, 100):
  prime = True
  for i in range(2, int(n/2)):
    if n % i == 0:
      prime = False
  if prime: 
    num_primes += 1

print("There are", num_primes, "primes under 100")

There are 26 primes under 100

### Password Validation

Now, we return to the problem from the beginning of class. Ask the user for a password. The password must be at least 8 characters long. If the password is not at least 8 characters long, reject the password and ask again.

In [15]:
# Your Code Here

password = input("Please enter a password:")
while len(password) < 8: 
  print("Error, your password must be at least 8 characters long, yours was", len(password))
  password = input("Please enter a password:")

print("Password Saved!")

Please enter a password:asdfasfh
Password Saved!

# Bonus: Palindrome Numbers

Imagine you're really interested in palidrome numbers, that is numbers which are the same forwards and backwards, for example `303` , `1221`, or `1246421`. To do this, we'd need to first think about how you would reverse the digits of a number. One way would be to turn it into a string and reverse the string: 

```
a = 12454132
a_str = str(a)
# reverses the string
a_str = a_str[::-1]
print(a_str)
```

However, this is a little bit confusing and the conversion between integer and string isn't terribly efficient. There's a way to do it with just math and loops. Can you figure it out?

In [16]:
a = 12454132
# Your code here
a_copy = a
a_reversed = 0

while a_copy > 0:
  # "move" the last digit to the left
  a_reversed *= 10

  # make the last digit of a_copy the last
  # digit of a_reversed
  a_reversed += a_copy % 10

  # "remove" the last digit 
  a_copy = int(a_copy/10)

print(a_reversed)

23145421

Now, write a script which determines if a number is a palindrome.

In [17]:
# Your code here
a = 1331
a_copy = a
a_reversed = 0

while a_copy > 0:
  # "move" the last digit to the left
  a_reversed *= 10

  # make the last digit of a_copy the last
  # digit of a_reversed
  a_reversed += a_copy % 10

  # "remove" the last digit 
  a_copy = int(a_copy/10)

if a_reversed == a:
  print(a, "is a palindrome")
else: 
  print(a, "is NOT palindrome")

1331 is a palindrome

# References
<sup>1</sup>[W3 Schools `while` Loop Page](https://www.w3schools.com/python/python_while_loops.asp)

<sup>2</sup>The NBA has a way for accessing states using Python, called the [nba_api](https://pypi.org/project/nba-api/)