# Teacher version

## Warm-up

Calculate the mean and median of the following set of numbers: 

$$
\{1, 2, 10, 32, 2, 10\}
$$

# Part 1: Some Tools

## Sum

Python has a bunch of tools that will help us calculate statistics. For example, let's look at the sum function: 

```
data = [1, 2, 10, 32, 2, 10]
result = sum(data) # we can use sum to calculate the sum of a dataset
```

Calculate and print the sum of the dataset below.

In [1]:
data = [100, 23, 109, 3000, 12, 15, 259, 238]
# your code here
print("The sum of the data is", sum(data))

The sum of the data is 3756

## Length

Now the `len` tool to count how many pieces of data there are (the "length")

```
data = [1, 2, 10, 32, 2, 10]
result = len(data) # we can use len to count the NUMBER OF DATA POINTS
```

Calculate and print the length of the dataset below.

In [2]:
data = [100, 23, 109, 3000, 12, 15, 259, 238]
# your code here
print("The number of the data points is", len(data))

The number of the data points is 8

# Accessing pieces of data
Let's say I want to print or perform a calculation on JUST ONE of the numbers in a dataset. Well, I can use something like this in Python: 

```
data = [1, 2, 10, 32, 2, 10]

print(data[0]) # will give the FIRST element -> 1
print(data[1]) # will give the SECOND element -> 2
print(data[2]) # will give the THIRD element -> 3
```

**Before running the code below**, try to guess what will be the result

In [3]:
data = [1, 2, 10, 32, 2, 10]
print(data[3] + 100)

132

Calculate and print **two times** the **fourth** element in the data below.

In [4]:
data = [100, 23, 109, 3000, 12, 15, 259, 238]
# your code here
print("Two times the fourth element is", 2*data[3]) # remember that it needs to be 4-1 in the brackets

Two times the fourth element is 6000

# Part 2: Finding the Mean and Median

Now, given these pieces of information, how would you calculate the mean? Below, calculate and print:
- the number of elements in the data
- the sum of the data
- the mean of the data
- the median of the data

In [5]:
# data is in order
data = [2, 4, 10, 10, 15, 23, 25, 27, 38, 41, 45, 45, 56, 65, 79, 90, 105, 127, 130, 138, 140, 144, 146, 146, 153, 156, 160, 163, 164, 169, 170, 176, 182, 194]
# your code here
print("The sum of the data is", sum(data))
print("The number of the data points is", len(data))
print("The mean is", sum(data)/len(data))
median_location = int(len(data)/2)
print("The median is", data[median_location])

The sum of the data is 3338
The number of the data points is 34
The mean is 98.17647058823529
The median is 127

# Bonus 

If you finish quickly, consider the following problem: 

You're a math teacher in a high school which gives their students a lot of exams. You were gave an exam on Monday. However, one student, Sam, was absent and had to take the test on Wednesday. Since it was only one person, you didn't bother to make a new version of the exam for the make-up on Wednesday. However, you want to check to make sure Sam didn't cheat by discussing the exam with classmates who'd taken in on Monday. Sam got a 91% on the make-up test.

Below is the data of: 
- Monday test takers scores on this exam
- Sams previous exam scores

Using the mean/median to decide if you think Sam might have cheated.

In [6]:
monday_test_scores = [60, 61, 64, 70, 70, 80, 83, 83, 83, 84, 88, 91, 91, 95, 99, 99, 99, 100]
sams_previous_scores = [75, 78, 81, 82, 87]

# Your code here
print("The average test score on monday was:", sum(monday_test_scores)/len(monday_test_scores))
print("The median test score on monday was:", monday_test_scores[int(len(monday_test_scores)/2)])
print("Sam's previous average test score was:", sum(sams_previous_scores)/len(sams_previous_scores))

The average test score on monday was: 83.33333333333333
The median test score on monday was: 84
Sam's previous average test score was: 80.6

Based on this data, it seems possible that Sam cheated. Sam scored almost 10 points higher than Sam's average from previous exams and 6-7 points higher than the average of the whole class. If Sam didn't cheat, you might expect Sam to score either similar to Sam's average from previous tests or closer to the average of the class. While this evidence couldn't be used to *prove* Sam cheated, it's certainly cause for suspicion.

To enhance this analysis, we might want to look at how far from the average Sam usually performs as well. Why do you think that might be more reliable than just caluclating the average?